packages:
    github.com/Android12349/food_recomendation/profile_managment_service/internal/services/profile_service:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            filename: "mocks.go"
            pkgname: "mocks"
            structname: "{{.InterfaceName}}"
        interfaces:
            ProfileStorage:

