// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/meal_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MealModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ProductIds    []int32                `protobuf:"varint,4,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealModel) Reset() {
	*x = MealModel{}
	mi := &file_models_meal_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealModel) ProtoMessage() {}

func (x *MealModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_meal_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealModel.ProtoReflect.Descriptor instead.
func (*MealModel) Descriptor() ([]byte, []int) {
	return file_models_meal_model_proto_rawDescGZIP(), []int{0}
}

func (x *MealModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MealModel) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MealModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealModel) GetProductIds() []int32 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *MealModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type MealCreateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ProductIds    []int32                `protobuf:"varint,3,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealCreateModel) Reset() {
	*x = MealCreateModel{}
	mi := &file_models_meal_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealCreateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealCreateModel) ProtoMessage() {}

func (x *MealCreateModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_meal_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealCreateModel.ProtoReflect.Descriptor instead.
func (*MealCreateModel) Descriptor() ([]byte, []int) {
	return file_models_meal_model_proto_rawDescGZIP(), []int{1}
}

func (x *MealCreateModel) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MealCreateModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealCreateModel) GetProductIds() []int32 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type MealUpdateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ProductIds    []int32                `protobuf:"varint,2,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MealUpdateModel) Reset() {
	*x = MealUpdateModel{}
	mi := &file_models_meal_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MealUpdateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MealUpdateModel) ProtoMessage() {}

func (x *MealUpdateModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_meal_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MealUpdateModel.ProtoReflect.Descriptor instead.
func (*MealUpdateModel) Descriptor() ([]byte, []int) {
	return file_models_meal_model_proto_rawDescGZIP(), []int{2}
}

func (x *MealUpdateModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MealUpdateModel) GetProductIds() []int32 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

var File_models_meal_model_proto protoreflect.FileDescriptor

const file_models_meal_model_proto_rawDesc = "" +
	"\n" +
	"\x17models/meal_model.proto\x12\x1cprofile_management.models.v1\"\x88\x01\n" +
	"\tMealModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vproduct_ids\x18\x04 \x03(\x05R\n" +
	"productIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"_\n" +
	"\x0fMealCreateModel\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vproduct_ids\x18\x03 \x03(\x05R\n" +
	"productIds\"F\n" +
	"\x0fMealUpdateModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\x05R\n" +
	"productIdsBYZWgithub.com/Android12349/food_recomendation/profile_managment_service/internal/pb/modelsb\x06proto3"

var (
	file_models_meal_model_proto_rawDescOnce sync.Once
	file_models_meal_model_proto_rawDescData []byte
)

func file_models_meal_model_proto_rawDescGZIP() []byte {
	file_models_meal_model_proto_rawDescOnce.Do(func() {
		file_models_meal_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_meal_model_proto_rawDesc), len(file_models_meal_model_proto_rawDesc)))
	})
	return file_models_meal_model_proto_rawDescData
}

var file_models_meal_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_meal_model_proto_goTypes = []any{
	(*MealModel)(nil),       // 0: profile_management.models.v1.MealModel
	(*MealCreateModel)(nil), // 1: profile_management.models.v1.MealCreateModel
	(*MealUpdateModel)(nil), // 2: profile_management.models.v1.MealUpdateModel
}
var file_models_meal_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_meal_model_proto_init() }
func file_models_meal_model_proto_init() {
	if File_models_meal_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_meal_model_proto_rawDesc), len(file_models_meal_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_meal_model_proto_goTypes,
		DependencyIndexes: file_models_meal_model_proto_depIdxs,
		MessageInfos:      file_models_meal_model_proto_msgTypes,
	}.Build()
	File_models_meal_model_proto = out.File
	file_models_meal_model_proto_goTypes = nil
	file_models_meal_model_proto_depIdxs = nil
}
