// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/product_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Calories      int32                  `protobuf:"varint,4,opt,name=calories,proto3" json:"calories,omitempty"`
	Protein       int32                  `protobuf:"varint,5,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           int32                  `protobuf:"varint,6,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         int32                  `protobuf:"varint,7,opt,name=carbs,proto3" json:"carbs,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductModel) Reset() {
	*x = ProductModel{}
	mi := &file_models_product_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductModel) ProtoMessage() {}

func (x *ProductModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_product_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductModel.ProtoReflect.Descriptor instead.
func (*ProductModel) Descriptor() ([]byte, []int) {
	return file_models_product_model_proto_rawDescGZIP(), []int{0}
}

func (x *ProductModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductModel) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProductModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductModel) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *ProductModel) GetProtein() int32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *ProductModel) GetFat() int32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *ProductModel) GetCarbs() int32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

func (x *ProductModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ProductCreateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Calories      int32                  `protobuf:"varint,3,opt,name=calories,proto3" json:"calories,omitempty"`
	Protein       int32                  `protobuf:"varint,4,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           int32                  `protobuf:"varint,5,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         int32                  `protobuf:"varint,6,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductCreateModel) Reset() {
	*x = ProductCreateModel{}
	mi := &file_models_product_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductCreateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductCreateModel) ProtoMessage() {}

func (x *ProductCreateModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_product_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductCreateModel.ProtoReflect.Descriptor instead.
func (*ProductCreateModel) Descriptor() ([]byte, []int) {
	return file_models_product_model_proto_rawDescGZIP(), []int{1}
}

func (x *ProductCreateModel) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ProductCreateModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductCreateModel) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *ProductCreateModel) GetProtein() int32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *ProductCreateModel) GetFat() int32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *ProductCreateModel) GetCarbs() int32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

type ProductUpdateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Calories      int32                  `protobuf:"varint,2,opt,name=calories,proto3" json:"calories,omitempty"`
	Protein       int32                  `protobuf:"varint,3,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           int32                  `protobuf:"varint,4,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         int32                  `protobuf:"varint,5,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductUpdateModel) Reset() {
	*x = ProductUpdateModel{}
	mi := &file_models_product_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductUpdateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductUpdateModel) ProtoMessage() {}

func (x *ProductUpdateModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_product_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductUpdateModel.ProtoReflect.Descriptor instead.
func (*ProductUpdateModel) Descriptor() ([]byte, []int) {
	return file_models_product_model_proto_rawDescGZIP(), []int{2}
}

func (x *ProductUpdateModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductUpdateModel) GetCalories() int32 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *ProductUpdateModel) GetProtein() int32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *ProductUpdateModel) GetFat() int32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *ProductUpdateModel) GetCarbs() int32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

var File_models_product_model_proto protoreflect.FileDescriptor

const file_models_product_model_proto_rawDesc = "" +
	"\n" +
	"\x1amodels/product_model.proto\x12\x1cprofile_management.models.v1\"\xc8\x01\n" +
	"\fProductModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcalories\x18\x04 \x01(\x05R\bcalories\x12\x18\n" +
	"\aprotein\x18\x05 \x01(\x05R\aprotein\x12\x10\n" +
	"\x03fat\x18\x06 \x01(\x05R\x03fat\x12\x14\n" +
	"\x05carbs\x18\a \x01(\x05R\x05carbs\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x9f\x01\n" +
	"\x12ProductCreateModel\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcalories\x18\x03 \x01(\x05R\bcalories\x12\x18\n" +
	"\aprotein\x18\x04 \x01(\x05R\aprotein\x12\x10\n" +
	"\x03fat\x18\x05 \x01(\x05R\x03fat\x12\x14\n" +
	"\x05carbs\x18\x06 \x01(\x05R\x05carbs\"\x86\x01\n" +
	"\x12ProductUpdateModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bcalories\x18\x02 \x01(\x05R\bcalories\x12\x18\n" +
	"\aprotein\x18\x03 \x01(\x05R\aprotein\x12\x10\n" +
	"\x03fat\x18\x04 \x01(\x05R\x03fat\x12\x14\n" +
	"\x05carbs\x18\x05 \x01(\x05R\x05carbsBYZWgithub.com/Android12349/food_recomendation/profile_managment_service/internal/pb/modelsb\x06proto3"

var (
	file_models_product_model_proto_rawDescOnce sync.Once
	file_models_product_model_proto_rawDescData []byte
)

func file_models_product_model_proto_rawDescGZIP() []byte {
	file_models_product_model_proto_rawDescOnce.Do(func() {
		file_models_product_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_product_model_proto_rawDesc), len(file_models_product_model_proto_rawDesc)))
	})
	return file_models_product_model_proto_rawDescData
}

var file_models_product_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_product_model_proto_goTypes = []any{
	(*ProductModel)(nil),       // 0: profile_management.models.v1.ProductModel
	(*ProductCreateModel)(nil), // 1: profile_management.models.v1.ProductCreateModel
	(*ProductUpdateModel)(nil), // 2: profile_management.models.v1.ProductUpdateModel
}
var file_models_product_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_product_model_proto_init() }
func file_models_product_model_proto_init() {
	if File_models_product_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_product_model_proto_rawDesc), len(file_models_product_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_product_model_proto_goTypes,
		DependencyIndexes: file_models_product_model_proto_depIdxs,
		MessageInfos:      file_models_product_model_proto_msgTypes,
	}.Build()
	File_models_product_model_proto = out.File
	file_models_product_model_proto_goTypes = nil
	file_models_product_model_proto_depIdxs = nil
}
