// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: models/user_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Bju           *BJUModel              `protobuf:"bytes,6,opt,name=bju,proto3" json:"bju,omitempty"`
	Budget        int32                  `protobuf:"varint,7,opt,name=budget,proto3" json:"budget,omitempty"`
	Preferences   string                 `protobuf:"bytes,8,opt,name=preferences,proto3" json:"preferences,omitempty"` // JSON string
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserModel) Reset() {
	*x = UserModel{}
	mi := &file_models_user_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserModel) ProtoMessage() {}

func (x *UserModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserModel.ProtoReflect.Descriptor instead.
func (*UserModel) Descriptor() ([]byte, []int) {
	return file_models_user_model_proto_rawDescGZIP(), []int{0}
}

func (x *UserModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserModel) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserModel) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserModel) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UserModel) GetBju() *BJUModel {
	if x != nil {
		return x.Bju
	}
	return nil
}

func (x *UserModel) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *UserModel) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

func (x *UserModel) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type BJUModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protein       int32                  `protobuf:"varint,1,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           int32                  `protobuf:"varint,2,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbs         int32                  `protobuf:"varint,3,opt,name=carbs,proto3" json:"carbs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BJUModel) Reset() {
	*x = BJUModel{}
	mi := &file_models_user_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BJUModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BJUModel) ProtoMessage() {}

func (x *BJUModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BJUModel.ProtoReflect.Descriptor instead.
func (*BJUModel) Descriptor() ([]byte, []int) {
	return file_models_user_model_proto_rawDescGZIP(), []int{1}
}

func (x *BJUModel) GetProtein() int32 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *BJUModel) GetFat() int32 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *BJUModel) GetCarbs() int32 {
	if x != nil {
		return x.Carbs
	}
	return 0
}

type UserCreateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Weight        int32                  `protobuf:"varint,4,opt,name=weight,proto3" json:"weight,omitempty"`
	Bju           *BJUModel              `protobuf:"bytes,5,opt,name=bju,proto3" json:"bju,omitempty"`
	Budget        int32                  `protobuf:"varint,6,opt,name=budget,proto3" json:"budget,omitempty"`
	Preferences   string                 `protobuf:"bytes,7,opt,name=preferences,proto3" json:"preferences,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreateModel) Reset() {
	*x = UserCreateModel{}
	mi := &file_models_user_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreateModel) ProtoMessage() {}

func (x *UserCreateModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreateModel.ProtoReflect.Descriptor instead.
func (*UserCreateModel) Descriptor() ([]byte, []int) {
	return file_models_user_model_proto_rawDescGZIP(), []int{2}
}

func (x *UserCreateModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserCreateModel) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserCreateModel) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserCreateModel) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UserCreateModel) GetBju() *BJUModel {
	if x != nil {
		return x.Bju
	}
	return nil
}

func (x *UserCreateModel) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *UserCreateModel) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

type UserUpdateModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Weight        int32                  `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Bju           *BJUModel              `protobuf:"bytes,4,opt,name=bju,proto3" json:"bju,omitempty"`
	Budget        int32                  `protobuf:"varint,5,opt,name=budget,proto3" json:"budget,omitempty"`
	Preferences   string                 `protobuf:"bytes,6,opt,name=preferences,proto3" json:"preferences,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserUpdateModel) Reset() {
	*x = UserUpdateModel{}
	mi := &file_models_user_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdateModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdateModel) ProtoMessage() {}

func (x *UserUpdateModel) ProtoReflect() protoreflect.Message {
	mi := &file_models_user_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdateModel.ProtoReflect.Descriptor instead.
func (*UserUpdateModel) Descriptor() ([]byte, []int) {
	return file_models_user_model_proto_rawDescGZIP(), []int{3}
}

func (x *UserUpdateModel) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserUpdateModel) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UserUpdateModel) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UserUpdateModel) GetBju() *BJUModel {
	if x != nil {
		return x.Bju
	}
	return nil
}

func (x *UserUpdateModel) GetBudget() int32 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *UserUpdateModel) GetPreferences() string {
	if x != nil {
		return x.Preferences
	}
	return ""
}

var File_models_user_model_proto protoreflect.FileDescriptor

const file_models_user_model_proto_rawDesc = "" +
	"\n" +
	"\x17models/user_model.proto\x12\x1cprofile_management.models.v1\"\x9f\x02\n" +
	"\tUserModel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\x128\n" +
	"\x03bju\x18\x06 \x01(\v2&.profile_management.models.v1.BJUModelR\x03bju\x12\x16\n" +
	"\x06budget\x18\a \x01(\x05R\x06budget\x12 \n" +
	"\vpreferences\x18\b \x01(\tR\vpreferences\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"L\n" +
	"\bBJUModel\x12\x18\n" +
	"\aprotein\x18\x01 \x01(\x05R\aprotein\x12\x10\n" +
	"\x03fat\x18\x02 \x01(\x05R\x03fat\x12\x14\n" +
	"\x05carbs\x18\x03 \x01(\x05R\x05carbs\"\xed\x01\n" +
	"\x0fUserCreateModel\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x05R\x06weight\x128\n" +
	"\x03bju\x18\x05 \x01(\v2&.profile_management.models.v1.BJUModelR\x03bju\x12\x16\n" +
	"\x06budget\x18\x06 \x01(\x05R\x06budget\x12 \n" +
	"\vpreferences\x18\a \x01(\tR\vpreferences\"\xd1\x01\n" +
	"\x0fUserUpdateModel\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x05R\x06weight\x128\n" +
	"\x03bju\x18\x04 \x01(\v2&.profile_management.models.v1.BJUModelR\x03bju\x12\x16\n" +
	"\x06budget\x18\x05 \x01(\x05R\x06budget\x12 \n" +
	"\vpreferences\x18\x06 \x01(\tR\vpreferencesBYZWgithub.com/Android12349/food_recomendation/profile_managment_service/internal/pb/modelsb\x06proto3"

var (
	file_models_user_model_proto_rawDescOnce sync.Once
	file_models_user_model_proto_rawDescData []byte
)

func file_models_user_model_proto_rawDescGZIP() []byte {
	file_models_user_model_proto_rawDescOnce.Do(func() {
		file_models_user_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_user_model_proto_rawDesc), len(file_models_user_model_proto_rawDesc)))
	})
	return file_models_user_model_proto_rawDescData
}

var file_models_user_model_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_models_user_model_proto_goTypes = []any{
	(*UserModel)(nil),       // 0: profile_management.models.v1.UserModel
	(*BJUModel)(nil),        // 1: profile_management.models.v1.BJUModel
	(*UserCreateModel)(nil), // 2: profile_management.models.v1.UserCreateModel
	(*UserUpdateModel)(nil), // 3: profile_management.models.v1.UserUpdateModel
}
var file_models_user_model_proto_depIdxs = []int32{
	1, // 0: profile_management.models.v1.UserModel.bju:type_name -> profile_management.models.v1.BJUModel
	1, // 1: profile_management.models.v1.UserCreateModel.bju:type_name -> profile_management.models.v1.BJUModel
	1, // 2: profile_management.models.v1.UserUpdateModel.bju:type_name -> profile_management.models.v1.BJUModel
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_models_user_model_proto_init() }
func file_models_user_model_proto_init() {
	if File_models_user_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_user_model_proto_rawDesc), len(file_models_user_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_user_model_proto_goTypes,
		DependencyIndexes: file_models_user_model_proto_depIdxs,
		MessageInfos:      file_models_user_model_proto_msgTypes,
	}.Build()
	File_models_user_model_proto = out.File
	file_models_user_model_proto_goTypes = nil
	file_models_user_model_proto_depIdxs = nil
}
