// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: profile_management_api/profile_management.proto

package profile_management_api

import (
	models "github.com/Android12349/food_recomendation/profile_managment_service/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User messages
type CreateUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	User          *models.UserCreateModel `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetUser() *models.UserCreateModel {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.UserModel      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetUser() *models.UserModel {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.UserModel      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetUser() *models.UserModel {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *models.UserUpdateModel `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetUser() *models.UserUpdateModel {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *models.UserModel      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserResponse) GetUser() *models.UserModel {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{7}
}

// Product messages
type CreateProductRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Product       *models.ProductCreateModel `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductRequest) GetProduct() *models.ProductCreateModel {
	if x != nil {
		return x.Product
	}
	return nil
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *models.ProductModel   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{9}
}

func (x *CreateProductResponse) GetProduct() *models.ProductModel {
	if x != nil {
		return x.Product
	}
	return nil
}

type GetProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsRequest) Reset() {
	*x = GetProductsRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsRequest) ProtoMessage() {}

func (x *GetProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{10}
}

func (x *GetProductsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*models.ProductModel `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsResponse) Reset() {
	*x = GetProductsResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsResponse) ProtoMessage() {}

func (x *GetProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{11}
}

func (x *GetProductsResponse) GetProducts() []*models.ProductModel {
	if x != nil {
		return x.Products
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Product       *models.ProductUpdateModel `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetProduct() *models.ProductUpdateModel {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *models.ProductModel   `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateProductResponse) GetProduct() *models.ProductModel {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteProductRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{15}
}

// Meal messages
type CreateMealRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Meal          *models.MealCreateModel `protobuf:"bytes,1,opt,name=meal,proto3" json:"meal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMealRequest) Reset() {
	*x = CreateMealRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMealRequest) ProtoMessage() {}

func (x *CreateMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMealRequest.ProtoReflect.Descriptor instead.
func (*CreateMealRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{16}
}

func (x *CreateMealRequest) GetMeal() *models.MealCreateModel {
	if x != nil {
		return x.Meal
	}
	return nil
}

type CreateMealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meal          *models.MealModel      `protobuf:"bytes,1,opt,name=meal,proto3" json:"meal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMealResponse) Reset() {
	*x = CreateMealResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMealResponse) ProtoMessage() {}

func (x *CreateMealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMealResponse.ProtoReflect.Descriptor instead.
func (*CreateMealResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{17}
}

func (x *CreateMealResponse) GetMeal() *models.MealModel {
	if x != nil {
		return x.Meal
	}
	return nil
}

type GetMealsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsRequest) Reset() {
	*x = GetMealsRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsRequest) ProtoMessage() {}

func (x *GetMealsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsRequest.ProtoReflect.Descriptor instead.
func (*GetMealsRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{18}
}

func (x *GetMealsRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMealsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meals         []*models.MealModel    `protobuf:"bytes,1,rep,name=meals,proto3" json:"meals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMealsResponse) Reset() {
	*x = GetMealsResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMealsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMealsResponse) ProtoMessage() {}

func (x *GetMealsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMealsResponse.ProtoReflect.Descriptor instead.
func (*GetMealsResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{19}
}

func (x *GetMealsResponse) GetMeals() []*models.MealModel {
	if x != nil {
		return x.Meals
	}
	return nil
}

type UpdateMealRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Meal          *models.MealUpdateModel `protobuf:"bytes,2,opt,name=meal,proto3" json:"meal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMealRequest) Reset() {
	*x = UpdateMealRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMealRequest) ProtoMessage() {}

func (x *UpdateMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMealRequest.ProtoReflect.Descriptor instead.
func (*UpdateMealRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateMealRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateMealRequest) GetMeal() *models.MealUpdateModel {
	if x != nil {
		return x.Meal
	}
	return nil
}

type UpdateMealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meal          *models.MealModel      `protobuf:"bytes,1,opt,name=meal,proto3" json:"meal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMealResponse) Reset() {
	*x = UpdateMealResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMealResponse) ProtoMessage() {}

func (x *UpdateMealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMealResponse.ProtoReflect.Descriptor instead.
func (*UpdateMealResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateMealResponse) GetMeal() *models.MealModel {
	if x != nil {
		return x.Meal
	}
	return nil
}

type DeleteMealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMealRequest) Reset() {
	*x = DeleteMealRequest{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMealRequest) ProtoMessage() {}

func (x *DeleteMealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMealRequest.ProtoReflect.Descriptor instead.
func (*DeleteMealRequest) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteMealRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMealResponse) Reset() {
	*x = DeleteMealResponse{}
	mi := &file_profile_management_api_profile_management_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMealResponse) ProtoMessage() {}

func (x *DeleteMealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profile_management_api_profile_management_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMealResponse.ProtoReflect.Descriptor instead.
func (*DeleteMealResponse) Descriptor() ([]byte, []int) {
	return file_profile_management_api_profile_management_proto_rawDescGZIP(), []int{23}
}

var File_profile_management_api_profile_management_proto protoreflect.FileDescriptor

const file_profile_management_api_profile_management_proto_rawDesc = "" +
	"\n" +
	"/profile_management_api/profile_management.proto\x12\x1dprofile_management.service.v1\x1a\x17models/user_model.proto\x1a\x1amodels/product_model.proto\x1a\x17models/meal_model.proto\x1a\x1cgoogle/api/annotations.proto\"V\n" +
	"\x11CreateUserRequest\x12A\n" +
	"\x04user\x18\x01 \x01(\v2-.profile_management.models.v1.UserCreateModelR\x04user\"Q\n" +
	"\x12CreateUserResponse\x12;\n" +
	"\x04user\x18\x01 \x01(\v2'.profile_management.models.v1.UserModelR\x04user\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"N\n" +
	"\x0fGetUserResponse\x12;\n" +
	"\x04user\x18\x01 \x01(\v2'.profile_management.models.v1.UserModelR\x04user\"f\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12A\n" +
	"\x04user\x18\x02 \x01(\v2-.profile_management.models.v1.UserUpdateModelR\x04user\"Q\n" +
	"\x12UpdateUserResponse\x12;\n" +
	"\x04user\x18\x01 \x01(\v2'.profile_management.models.v1.UserModelR\x04user\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x14\n" +
	"\x12DeleteUserResponse\"b\n" +
	"\x14CreateProductRequest\x12J\n" +
	"\aproduct\x18\x01 \x01(\v20.profile_management.models.v1.ProductCreateModelR\aproduct\"]\n" +
	"\x15CreateProductResponse\x12D\n" +
	"\aproduct\x18\x01 \x01(\v2*.profile_management.models.v1.ProductModelR\aproduct\"-\n" +
	"\x12GetProductsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"]\n" +
	"\x13GetProductsResponse\x12F\n" +
	"\bproducts\x18\x01 \x03(\v2*.profile_management.models.v1.ProductModelR\bproducts\"r\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12J\n" +
	"\aproduct\x18\x02 \x01(\v20.profile_management.models.v1.ProductUpdateModelR\aproduct\"]\n" +
	"\x15UpdateProductResponse\x12D\n" +
	"\aproduct\x18\x01 \x01(\v2*.profile_management.models.v1.ProductModelR\aproduct\"&\n" +
	"\x14DeleteProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x17\n" +
	"\x15DeleteProductResponse\"V\n" +
	"\x11CreateMealRequest\x12A\n" +
	"\x04meal\x18\x01 \x01(\v2-.profile_management.models.v1.MealCreateModelR\x04meal\"Q\n" +
	"\x12CreateMealResponse\x12;\n" +
	"\x04meal\x18\x01 \x01(\v2'.profile_management.models.v1.MealModelR\x04meal\"*\n" +
	"\x0fGetMealsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\"Q\n" +
	"\x10GetMealsResponse\x12=\n" +
	"\x05meals\x18\x01 \x03(\v2'.profile_management.models.v1.MealModelR\x05meals\"f\n" +
	"\x11UpdateMealRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12A\n" +
	"\x04meal\x18\x02 \x01(\v2-.profile_management.models.v1.MealUpdateModelR\x04meal\"Q\n" +
	"\x12UpdateMealResponse\x12;\n" +
	"\x04meal\x18\x01 \x01(\v2'.profile_management.models.v1.MealModelR\x04meal\"#\n" +
	"\x11DeleteMealRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x14\n" +
	"\x12DeleteMealResponse2\x98\r\n" +
	"\x18ProfileManagementService\x12\x84\x01\n" +
	"\n" +
	"CreateUser\x120.profile_management.service.v1.CreateUserRequest\x1a1.profile_management.service.v1.CreateUserResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/users\x12}\n" +
	"\aGetUser\x12-.profile_management.service.v1.GetUserRequest\x1a..profile_management.service.v1.GetUserResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/users/{id}\x12\x89\x01\n" +
	"\n" +
	"UpdateUser\x120.profile_management.service.v1.UpdateUserRequest\x1a1.profile_management.service.v1.UpdateUserResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*2\v/users/{id}\x12\x86\x01\n" +
	"\n" +
	"DeleteUser\x120.profile_management.service.v1.DeleteUserRequest\x1a1.profile_management.service.v1.DeleteUserResponse\"\x13\x82\xd3\xe4\x93\x02\r*\v/users/{id}\x12\x90\x01\n" +
	"\rCreateProduct\x123.profile_management.service.v1.CreateProductRequest\x1a4.profile_management.service.v1.CreateProductResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/products\x12\x87\x01\n" +
	"\vGetProducts\x121.profile_management.service.v1.GetProductsRequest\x1a2.profile_management.service.v1.GetProductsResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/products\x12\x95\x01\n" +
	"\rUpdateProduct\x123.profile_management.service.v1.UpdateProductRequest\x1a4.profile_management.service.v1.UpdateProductResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*2\x0e/products/{id}\x12\x92\x01\n" +
	"\rDeleteProduct\x123.profile_management.service.v1.DeleteProductRequest\x1a4.profile_management.service.v1.DeleteProductResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/products/{id}\x12\x84\x01\n" +
	"\n" +
	"CreateMeal\x120.profile_management.service.v1.CreateMealRequest\x1a1.profile_management.service.v1.CreateMealResponse\"\x11\x82\xd3\xe4\x93\x02\v:\x01*\"\x06/meals\x12{\n" +
	"\bGetMeals\x12..profile_management.service.v1.GetMealsRequest\x1a/.profile_management.service.v1.GetMealsResponse\"\x0e\x82\xd3\xe4\x93\x02\b\x12\x06/meals\x12\x89\x01\n" +
	"\n" +
	"UpdateMeal\x120.profile_management.service.v1.UpdateMealRequest\x1a1.profile_management.service.v1.UpdateMealResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*2\v/meals/{id}\x12\x86\x01\n" +
	"\n" +
	"DeleteMeal\x120.profile_management.service.v1.DeleteMealRequest\x1a1.profile_management.service.v1.DeleteMealResponse\"\x13\x82\xd3\xe4\x93\x02\r*\v/meals/{id}BiZggithub.com/Android12349/food_recomendation/profile_managment_service/internal/pb/profile_management_apib\x06proto3"

var (
	file_profile_management_api_profile_management_proto_rawDescOnce sync.Once
	file_profile_management_api_profile_management_proto_rawDescData []byte
)

func file_profile_management_api_profile_management_proto_rawDescGZIP() []byte {
	file_profile_management_api_profile_management_proto_rawDescOnce.Do(func() {
		file_profile_management_api_profile_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_management_api_profile_management_proto_rawDesc), len(file_profile_management_api_profile_management_proto_rawDesc)))
	})
	return file_profile_management_api_profile_management_proto_rawDescData
}

var file_profile_management_api_profile_management_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_profile_management_api_profile_management_proto_goTypes = []any{
	(*CreateUserRequest)(nil),         // 0: profile_management.service.v1.CreateUserRequest
	(*CreateUserResponse)(nil),        // 1: profile_management.service.v1.CreateUserResponse
	(*GetUserRequest)(nil),            // 2: profile_management.service.v1.GetUserRequest
	(*GetUserResponse)(nil),           // 3: profile_management.service.v1.GetUserResponse
	(*UpdateUserRequest)(nil),         // 4: profile_management.service.v1.UpdateUserRequest
	(*UpdateUserResponse)(nil),        // 5: profile_management.service.v1.UpdateUserResponse
	(*DeleteUserRequest)(nil),         // 6: profile_management.service.v1.DeleteUserRequest
	(*DeleteUserResponse)(nil),        // 7: profile_management.service.v1.DeleteUserResponse
	(*CreateProductRequest)(nil),      // 8: profile_management.service.v1.CreateProductRequest
	(*CreateProductResponse)(nil),     // 9: profile_management.service.v1.CreateProductResponse
	(*GetProductsRequest)(nil),        // 10: profile_management.service.v1.GetProductsRequest
	(*GetProductsResponse)(nil),       // 11: profile_management.service.v1.GetProductsResponse
	(*UpdateProductRequest)(nil),      // 12: profile_management.service.v1.UpdateProductRequest
	(*UpdateProductResponse)(nil),     // 13: profile_management.service.v1.UpdateProductResponse
	(*DeleteProductRequest)(nil),      // 14: profile_management.service.v1.DeleteProductRequest
	(*DeleteProductResponse)(nil),     // 15: profile_management.service.v1.DeleteProductResponse
	(*CreateMealRequest)(nil),         // 16: profile_management.service.v1.CreateMealRequest
	(*CreateMealResponse)(nil),        // 17: profile_management.service.v1.CreateMealResponse
	(*GetMealsRequest)(nil),           // 18: profile_management.service.v1.GetMealsRequest
	(*GetMealsResponse)(nil),          // 19: profile_management.service.v1.GetMealsResponse
	(*UpdateMealRequest)(nil),         // 20: profile_management.service.v1.UpdateMealRequest
	(*UpdateMealResponse)(nil),        // 21: profile_management.service.v1.UpdateMealResponse
	(*DeleteMealRequest)(nil),         // 22: profile_management.service.v1.DeleteMealRequest
	(*DeleteMealResponse)(nil),        // 23: profile_management.service.v1.DeleteMealResponse
	(*models.UserCreateModel)(nil),    // 24: profile_management.models.v1.UserCreateModel
	(*models.UserModel)(nil),          // 25: profile_management.models.v1.UserModel
	(*models.UserUpdateModel)(nil),    // 26: profile_management.models.v1.UserUpdateModel
	(*models.ProductCreateModel)(nil), // 27: profile_management.models.v1.ProductCreateModel
	(*models.ProductModel)(nil),       // 28: profile_management.models.v1.ProductModel
	(*models.ProductUpdateModel)(nil), // 29: profile_management.models.v1.ProductUpdateModel
	(*models.MealCreateModel)(nil),    // 30: profile_management.models.v1.MealCreateModel
	(*models.MealModel)(nil),          // 31: profile_management.models.v1.MealModel
	(*models.MealUpdateModel)(nil),    // 32: profile_management.models.v1.MealUpdateModel
}
var file_profile_management_api_profile_management_proto_depIdxs = []int32{
	24, // 0: profile_management.service.v1.CreateUserRequest.user:type_name -> profile_management.models.v1.UserCreateModel
	25, // 1: profile_management.service.v1.CreateUserResponse.user:type_name -> profile_management.models.v1.UserModel
	25, // 2: profile_management.service.v1.GetUserResponse.user:type_name -> profile_management.models.v1.UserModel
	26, // 3: profile_management.service.v1.UpdateUserRequest.user:type_name -> profile_management.models.v1.UserUpdateModel
	25, // 4: profile_management.service.v1.UpdateUserResponse.user:type_name -> profile_management.models.v1.UserModel
	27, // 5: profile_management.service.v1.CreateProductRequest.product:type_name -> profile_management.models.v1.ProductCreateModel
	28, // 6: profile_management.service.v1.CreateProductResponse.product:type_name -> profile_management.models.v1.ProductModel
	28, // 7: profile_management.service.v1.GetProductsResponse.products:type_name -> profile_management.models.v1.ProductModel
	29, // 8: profile_management.service.v1.UpdateProductRequest.product:type_name -> profile_management.models.v1.ProductUpdateModel
	28, // 9: profile_management.service.v1.UpdateProductResponse.product:type_name -> profile_management.models.v1.ProductModel
	30, // 10: profile_management.service.v1.CreateMealRequest.meal:type_name -> profile_management.models.v1.MealCreateModel
	31, // 11: profile_management.service.v1.CreateMealResponse.meal:type_name -> profile_management.models.v1.MealModel
	31, // 12: profile_management.service.v1.GetMealsResponse.meals:type_name -> profile_management.models.v1.MealModel
	32, // 13: profile_management.service.v1.UpdateMealRequest.meal:type_name -> profile_management.models.v1.MealUpdateModel
	31, // 14: profile_management.service.v1.UpdateMealResponse.meal:type_name -> profile_management.models.v1.MealModel
	0,  // 15: profile_management.service.v1.ProfileManagementService.CreateUser:input_type -> profile_management.service.v1.CreateUserRequest
	2,  // 16: profile_management.service.v1.ProfileManagementService.GetUser:input_type -> profile_management.service.v1.GetUserRequest
	4,  // 17: profile_management.service.v1.ProfileManagementService.UpdateUser:input_type -> profile_management.service.v1.UpdateUserRequest
	6,  // 18: profile_management.service.v1.ProfileManagementService.DeleteUser:input_type -> profile_management.service.v1.DeleteUserRequest
	8,  // 19: profile_management.service.v1.ProfileManagementService.CreateProduct:input_type -> profile_management.service.v1.CreateProductRequest
	10, // 20: profile_management.service.v1.ProfileManagementService.GetProducts:input_type -> profile_management.service.v1.GetProductsRequest
	12, // 21: profile_management.service.v1.ProfileManagementService.UpdateProduct:input_type -> profile_management.service.v1.UpdateProductRequest
	14, // 22: profile_management.service.v1.ProfileManagementService.DeleteProduct:input_type -> profile_management.service.v1.DeleteProductRequest
	16, // 23: profile_management.service.v1.ProfileManagementService.CreateMeal:input_type -> profile_management.service.v1.CreateMealRequest
	18, // 24: profile_management.service.v1.ProfileManagementService.GetMeals:input_type -> profile_management.service.v1.GetMealsRequest
	20, // 25: profile_management.service.v1.ProfileManagementService.UpdateMeal:input_type -> profile_management.service.v1.UpdateMealRequest
	22, // 26: profile_management.service.v1.ProfileManagementService.DeleteMeal:input_type -> profile_management.service.v1.DeleteMealRequest
	1,  // 27: profile_management.service.v1.ProfileManagementService.CreateUser:output_type -> profile_management.service.v1.CreateUserResponse
	3,  // 28: profile_management.service.v1.ProfileManagementService.GetUser:output_type -> profile_management.service.v1.GetUserResponse
	5,  // 29: profile_management.service.v1.ProfileManagementService.UpdateUser:output_type -> profile_management.service.v1.UpdateUserResponse
	7,  // 30: profile_management.service.v1.ProfileManagementService.DeleteUser:output_type -> profile_management.service.v1.DeleteUserResponse
	9,  // 31: profile_management.service.v1.ProfileManagementService.CreateProduct:output_type -> profile_management.service.v1.CreateProductResponse
	11, // 32: profile_management.service.v1.ProfileManagementService.GetProducts:output_type -> profile_management.service.v1.GetProductsResponse
	13, // 33: profile_management.service.v1.ProfileManagementService.UpdateProduct:output_type -> profile_management.service.v1.UpdateProductResponse
	15, // 34: profile_management.service.v1.ProfileManagementService.DeleteProduct:output_type -> profile_management.service.v1.DeleteProductResponse
	17, // 35: profile_management.service.v1.ProfileManagementService.CreateMeal:output_type -> profile_management.service.v1.CreateMealResponse
	19, // 36: profile_management.service.v1.ProfileManagementService.GetMeals:output_type -> profile_management.service.v1.GetMealsResponse
	21, // 37: profile_management.service.v1.ProfileManagementService.UpdateMeal:output_type -> profile_management.service.v1.UpdateMealResponse
	23, // 38: profile_management.service.v1.ProfileManagementService.DeleteMeal:output_type -> profile_management.service.v1.DeleteMealResponse
	27, // [27:39] is the sub-list for method output_type
	15, // [15:27] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_profile_management_api_profile_management_proto_init() }
func file_profile_management_api_profile_management_proto_init() {
	if File_profile_management_api_profile_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_management_api_profile_management_proto_rawDesc), len(file_profile_management_api_profile_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_management_api_profile_management_proto_goTypes,
		DependencyIndexes: file_profile_management_api_profile_management_proto_depIdxs,
		MessageInfos:      file_profile_management_api_profile_management_proto_msgTypes,
	}.Build()
	File_profile_management_api_profile_management_proto = out.File
	file_profile_management_api_profile_management_proto_goTypes = nil
	file_profile_management_api_profile_management_proto_depIdxs = nil
}
