// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Android12349/food_recomendation/profile_managment_service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NewProfileStorage creates a new instance of ProfileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileStorage {
	mock := &ProfileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProfileStorage is an autogenerated mock type for the ProfileStorage type
type ProfileStorage struct {
	mock.Mock
}

type ProfileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *ProfileStorage) EXPECT() *ProfileStorage_Expecter {
	return &ProfileStorage_Expecter{mock: &_m.Mock}
}

// CreateMeal provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) CreateMeal(ctx context.Context, meal *models.Meal) error {
	ret := _mock.Called(ctx, meal)

	if len(ret) == 0 {
		panic("no return value specified for CreateMeal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Meal) error); ok {
		r0 = returnFunc(ctx, meal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_CreateMeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMeal'
type ProfileStorage_CreateMeal_Call struct {
	*mock.Call
}

// CreateMeal is a helper method to define mock.On call
//   - ctx context.Context
//   - meal *models.Meal
func (_e *ProfileStorage_Expecter) CreateMeal(ctx interface{}, meal interface{}) *ProfileStorage_CreateMeal_Call {
	return &ProfileStorage_CreateMeal_Call{Call: _e.mock.On("CreateMeal", ctx, meal)}
}

func (_c *ProfileStorage_CreateMeal_Call) Run(run func(ctx context.Context, meal *models.Meal)) *ProfileStorage_CreateMeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Meal
		if args[1] != nil {
			arg1 = args[1].(*models.Meal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_CreateMeal_Call) Return(err error) *ProfileStorage_CreateMeal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_CreateMeal_Call) RunAndReturn(run func(ctx context.Context, meal *models.Meal) error) *ProfileStorage_CreateMeal_Call {
	_c.Call.Return(run)
	return _c
}

// CreateProduct provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) CreateProduct(ctx context.Context, product *models.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type ProfileStorage_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product *models.Product
func (_e *ProfileStorage_Expecter) CreateProduct(ctx interface{}, product interface{}) *ProfileStorage_CreateProduct_Call {
	return &ProfileStorage_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, product)}
}

func (_c *ProfileStorage_CreateProduct_Call) Run(run func(ctx context.Context, product *models.Product)) *ProfileStorage_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Product
		if args[1] != nil {
			arg1 = args[1].(*models.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_CreateProduct_Call) Return(err error) *ProfileStorage_CreateProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_CreateProduct_Call) RunAndReturn(run func(ctx context.Context, product *models.Product) error) *ProfileStorage_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) CreateUser(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type ProfileStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *ProfileStorage_Expecter) CreateUser(ctx interface{}, user interface{}) *ProfileStorage_CreateUser_Call {
	return &ProfileStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user)}
}

func (_c *ProfileStorage_CreateUser_Call) Run(run func(ctx context.Context, user *models.User)) *ProfileStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_CreateUser_Call) Return(err error) *ProfileStorage_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *ProfileStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMeal provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) DeleteMeal(ctx context.Context, id int32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMeal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_DeleteMeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMeal'
type ProfileStorage_DeleteMeal_Call struct {
	*mock.Call
}

// DeleteMeal is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *ProfileStorage_Expecter) DeleteMeal(ctx interface{}, id interface{}) *ProfileStorage_DeleteMeal_Call {
	return &ProfileStorage_DeleteMeal_Call{Call: _e.mock.On("DeleteMeal", ctx, id)}
}

func (_c *ProfileStorage_DeleteMeal_Call) Run(run func(ctx context.Context, id int32)) *ProfileStorage_DeleteMeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_DeleteMeal_Call) Return(err error) *ProfileStorage_DeleteMeal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_DeleteMeal_Call) RunAndReturn(run func(ctx context.Context, id int32) error) *ProfileStorage_DeleteMeal_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProduct provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) DeleteProduct(ctx context.Context, id int32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_DeleteProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProduct'
type ProfileStorage_DeleteProduct_Call struct {
	*mock.Call
}

// DeleteProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *ProfileStorage_Expecter) DeleteProduct(ctx interface{}, id interface{}) *ProfileStorage_DeleteProduct_Call {
	return &ProfileStorage_DeleteProduct_Call{Call: _e.mock.On("DeleteProduct", ctx, id)}
}

func (_c *ProfileStorage_DeleteProduct_Call) Run(run func(ctx context.Context, id int32)) *ProfileStorage_DeleteProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_DeleteProduct_Call) Return(err error) *ProfileStorage_DeleteProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_DeleteProduct_Call) RunAndReturn(run func(ctx context.Context, id int32) error) *ProfileStorage_DeleteProduct_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) DeleteUser(ctx context.Context, id int32) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type ProfileStorage_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *ProfileStorage_Expecter) DeleteUser(ctx interface{}, id interface{}) *ProfileStorage_DeleteUser_Call {
	return &ProfileStorage_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *ProfileStorage_DeleteUser_Call) Run(run func(ctx context.Context, id int32)) *ProfileStorage_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_DeleteUser_Call) Return(err error) *ProfileStorage_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id int32) error) *ProfileStorage_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetMealByID provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) GetMealByID(ctx context.Context, id int32) (*models.Meal, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetMealByID")
	}

	var r0 *models.Meal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (*models.Meal, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) *models.Meal); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Meal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileStorage_GetMealByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMealByID'
type ProfileStorage_GetMealByID_Call struct {
	*mock.Call
}

// GetMealByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *ProfileStorage_Expecter) GetMealByID(ctx interface{}, id interface{}) *ProfileStorage_GetMealByID_Call {
	return &ProfileStorage_GetMealByID_Call{Call: _e.mock.On("GetMealByID", ctx, id)}
}

func (_c *ProfileStorage_GetMealByID_Call) Run(run func(ctx context.Context, id int32)) *ProfileStorage_GetMealByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_GetMealByID_Call) Return(meal *models.Meal, err error) *ProfileStorage_GetMealByID_Call {
	_c.Call.Return(meal, err)
	return _c
}

func (_c *ProfileStorage_GetMealByID_Call) RunAndReturn(run func(ctx context.Context, id int32) (*models.Meal, error)) *ProfileStorage_GetMealByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMealsByUserID provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) GetMealsByUserID(ctx context.Context, userID int32) ([]*models.Meal, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMealsByUserID")
	}

	var r0 []*models.Meal
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]*models.Meal, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []*models.Meal); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Meal)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileStorage_GetMealsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMealsByUserID'
type ProfileStorage_GetMealsByUserID_Call struct {
	*mock.Call
}

// GetMealsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
func (_e *ProfileStorage_Expecter) GetMealsByUserID(ctx interface{}, userID interface{}) *ProfileStorage_GetMealsByUserID_Call {
	return &ProfileStorage_GetMealsByUserID_Call{Call: _e.mock.On("GetMealsByUserID", ctx, userID)}
}

func (_c *ProfileStorage_GetMealsByUserID_Call) Run(run func(ctx context.Context, userID int32)) *ProfileStorage_GetMealsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_GetMealsByUserID_Call) Return(meals []*models.Meal, err error) *ProfileStorage_GetMealsByUserID_Call {
	_c.Call.Return(meals, err)
	return _c
}

func (_c *ProfileStorage_GetMealsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int32) ([]*models.Meal, error)) *ProfileStorage_GetMealsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) GetProductByID(ctx context.Context, id int32) (*models.Product, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (*models.Product, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) *models.Product); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileStorage_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type ProfileStorage_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *ProfileStorage_Expecter) GetProductByID(ctx interface{}, id interface{}) *ProfileStorage_GetProductByID_Call {
	return &ProfileStorage_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *ProfileStorage_GetProductByID_Call) Run(run func(ctx context.Context, id int32)) *ProfileStorage_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_GetProductByID_Call) Return(product *models.Product, err error) *ProfileStorage_GetProductByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *ProfileStorage_GetProductByID_Call) RunAndReturn(run func(ctx context.Context, id int32) (*models.Product, error)) *ProfileStorage_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductsByUserID provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) GetProductsByUserID(ctx context.Context, userID int32) ([]*models.Product, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsByUserID")
	}

	var r0 []*models.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) ([]*models.Product, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) []*models.Product); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileStorage_GetProductsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductsByUserID'
type ProfileStorage_GetProductsByUserID_Call struct {
	*mock.Call
}

// GetProductsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int32
func (_e *ProfileStorage_Expecter) GetProductsByUserID(ctx interface{}, userID interface{}) *ProfileStorage_GetProductsByUserID_Call {
	return &ProfileStorage_GetProductsByUserID_Call{Call: _e.mock.On("GetProductsByUserID", ctx, userID)}
}

func (_c *ProfileStorage_GetProductsByUserID_Call) Run(run func(ctx context.Context, userID int32)) *ProfileStorage_GetProductsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_GetProductsByUserID_Call) Return(products []*models.Product, err error) *ProfileStorage_GetProductsByUserID_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *ProfileStorage_GetProductsByUserID_Call) RunAndReturn(run func(ctx context.Context, userID int32) ([]*models.Product, error)) *ProfileStorage_GetProductsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) GetUserByID(ctx context.Context, id int32) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int32) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ProfileStorage_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type ProfileStorage_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *ProfileStorage_Expecter) GetUserByID(ctx interface{}, id interface{}) *ProfileStorage_GetUserByID_Call {
	return &ProfileStorage_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *ProfileStorage_GetUserByID_Call) Run(run func(ctx context.Context, id int32)) *ProfileStorage_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int32
		if args[1] != nil {
			arg1 = args[1].(int32)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_GetUserByID_Call) Return(user *models.User, err error) *ProfileStorage_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *ProfileStorage_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id int32) (*models.User, error)) *ProfileStorage_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMeal provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) UpdateMeal(ctx context.Context, meal *models.Meal) error {
	ret := _mock.Called(ctx, meal)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMeal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Meal) error); ok {
		r0 = returnFunc(ctx, meal)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_UpdateMeal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMeal'
type ProfileStorage_UpdateMeal_Call struct {
	*mock.Call
}

// UpdateMeal is a helper method to define mock.On call
//   - ctx context.Context
//   - meal *models.Meal
func (_e *ProfileStorage_Expecter) UpdateMeal(ctx interface{}, meal interface{}) *ProfileStorage_UpdateMeal_Call {
	return &ProfileStorage_UpdateMeal_Call{Call: _e.mock.On("UpdateMeal", ctx, meal)}
}

func (_c *ProfileStorage_UpdateMeal_Call) Run(run func(ctx context.Context, meal *models.Meal)) *ProfileStorage_UpdateMeal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Meal
		if args[1] != nil {
			arg1 = args[1].(*models.Meal)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_UpdateMeal_Call) Return(err error) *ProfileStorage_UpdateMeal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_UpdateMeal_Call) RunAndReturn(run func(ctx context.Context, meal *models.Meal) error) *ProfileStorage_UpdateMeal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProduct provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) UpdateProduct(ctx context.Context, product *models.Product) error {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Product) error); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_UpdateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProduct'
type ProfileStorage_UpdateProduct_Call struct {
	*mock.Call
}

// UpdateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - product *models.Product
func (_e *ProfileStorage_Expecter) UpdateProduct(ctx interface{}, product interface{}) *ProfileStorage_UpdateProduct_Call {
	return &ProfileStorage_UpdateProduct_Call{Call: _e.mock.On("UpdateProduct", ctx, product)}
}

func (_c *ProfileStorage_UpdateProduct_Call) Run(run func(ctx context.Context, product *models.Product)) *ProfileStorage_UpdateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Product
		if args[1] != nil {
			arg1 = args[1].(*models.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_UpdateProduct_Call) Return(err error) *ProfileStorage_UpdateProduct_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_UpdateProduct_Call) RunAndReturn(run func(ctx context.Context, product *models.Product) error) *ProfileStorage_UpdateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type ProfileStorage
func (_mock *ProfileStorage) UpdateUser(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProfileStorage_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type ProfileStorage_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *ProfileStorage_Expecter) UpdateUser(ctx interface{}, user interface{}) *ProfileStorage_UpdateUser_Call {
	return &ProfileStorage_UpdateUser_Call{Call: _e.mock.On("UpdateUser", ctx, user)}
}

func (_c *ProfileStorage_UpdateUser_Call) Run(run func(ctx context.Context, user *models.User)) *ProfileStorage_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ProfileStorage_UpdateUser_Call) Return(err error) *ProfileStorage_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProfileStorage_UpdateUser_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *ProfileStorage_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
